# Build scripts for GitLab CI. 

debian:
  image: juliangraham/gzochi-build
  script:
    - "export GUILE_CFLAGS=\"-pthread -I/usr/include/guile/2.0 -I/usr/include\""
    - "export GUILE_LIBS=\"-L/usr/lib -lguile-2.0 -lgc\""
    - "./autogen.sh"
    - "./configure"
    - "make"
    - "make check"
    